### ISSUE TITLE
How do you see the process instances?

### ISSUE THREAD

**Issue by jgammon612** [jbossdemocentral/rhdm7-qlb-loan-demo#11]
guys:
So using the init-openshift.sh from command line installs PAM and the QLB client. You manually import the project which is fine but a) how do I see a process instance state of a loan app? b) if the dmAdmin user is both an analyst and an admin, how do you show the different views? seems to me that the view will always be admin -- I don't see a way to select one of the roles that the dmAdmin has

**Comment by DuncanDoyle** [comment]
The demo actually installs Decision Manager and not PAM (Process Automation Manager). The demo does not start a process instance. It uses a BPMN2 file to describe a so called "ruleflow". The demo simply shows an AngularJS UI calling a rules service on Decision Server, which is implemented using various rule artefacts like a 'ruleflow', 'decision table', 'guided rule', etc.
